FROM jenkins/inbound-agent:latest

USER root

# Install tools
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Install kubectl (match cluster minor version)
RUN curl -LO https://dl.k8s.io/release/v1.31.2/bin/linux/amd64/kubectl \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

USER jenkins

