pipeline {
    agent {
        docker {
            image 'docker:24-cli'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        APP_NAME  = 'aiops-app'
        IMAGE_TAG = "jenkins-${env.BUILD_NUMBER}"
        IMAGE     = "${APP_NAME}:${IMAGE_TAG}"
        KUBECONFIG = '/root/.kube/config'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
            	    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                	url: 'https://github.com/roshaan1103/Military_Intelligence_AiOps_k8s.git',
                	credentialsId: 'github-cred'
            	    ]]
        	])
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker version
                docker build -t ${IMAGE} -f docker/Dockerfile .
                '''
            }
        }

        stage('Load Image into KIND') {
            steps {
                sh '''
                kind load docker-image ${IMAGE}
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl set image deployment/aiops-app aiops-app=${IMAGE} --record
                kubectl rollout status deployment/aiops-app
                '''
            }
        }
    }

    post {
        success {
            echo "Deployment successful: ${IMAGE}"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}

