pipeline {
  agent {
    kubernetes {
      label 'jenkins-agent'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args:
      - -webSocket
      - \$(JENKINS_SECRET)
      - \$(JENKINS_NAME)
"""
    }
  }

  stages {
    stage('Smoke') {
      steps {
        sh 'echo Connected to Kubernetes agent'
        sh 'env | grep JENKINS'
      }
    }
  }
}

